--- #YAML:1.0
name:               Rose-URI
version:            1.00
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    overload:      0
    perl:          5.006000
    Rose::Object:  0.015
    URI:           0
    URI::Escape:   0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-URI
    license:     http://dev.perl.org/licenses/
    repository:  http://rose.googlecode.com/svn/trunk/modules/Rose-URI
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
