# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose-URI
version:      0.011
version_from: lib/Rose/URI.pm
installdirs:  site
requires:
    overload:                      0
    Rose::Object:                  0
    URI:                           0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
