--- #YAML:1.0
name:                Rose-URI
version:             0.022
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    overload:                      0
    Rose::Object:                  0.015
    URI:                           0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
